[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"


